# Практическое задание №6

## Задание 1

Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.
Вычислите, по возможности не используя программирование: (5Е)–1, где Е – единичная матрица размера 5х5.

In [155]:
import numpy as np

E = np.array([[1,0,0,0,0],[0,1,0,0,0], [0,0,1,0,0], [0,0,0,1,0],[0,0,0,0,1]])

print('дана единичная матрица размером 5х5:\n\n'
      f'{E}\n\n'
      'вычислим  (5E)^(-1):\n'
      '(5E)^(-1) = 5^(-1) * E^(-1)\n'
      'единичная матрица транспонируется в единичную матрицу, значит:\n'
      '5^(-1) * E^(-1) = 5^(-1) * E, следовательно, мне нужно умножить каждый элемент матрицы на 5^(-1) :\n'
      '(5E)^(-1) = \n\n'
      '[[0.2,0,0,0,0]\n'
      '[0,0.2,0,0,0]\n' 
      '[0,0,0.2,0,0]\n' 
      '[0,0,0,0.2,0]\n'
      '[0,0,0,0,0.2]]\n\n'
      'проверим кодом:')

result = (5 ** - 1) * E.transpose()
print(result)

дана единичная матрица размером 5х5:

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

вычислим  (5E)^(-1):
(5E)^(-1) = 5^(-1) * E^(-1)
единичная матрица транспонируется в единичную матрицу, значит:
5^(-1) * E^(-1) = 5^(-1) * E, следовательно, мне нужно умножить каждый элемент матрицы на 5^(-1) :
(5E)^(-1) = 

[[0.2,0,0,0,0]
[0,0.2,0,0,0]
[0,0,0.2,0,0]
[0,0,0,0.2,0]
[0,0,0,0,0.2]]

проверим кодом:
[[0.2 0.  0.  0.  0. ]
 [0.  0.2 0.  0.  0. ]
 [0.  0.  0.2 0.  0. ]
 [0.  0.  0.  0.2 0. ]
 [0.  0.  0.  0.  0.2]]


## Задание 2

5.2. Вычислите определитель:
$$ 
\left[
  \begin{array}{ccc}
    {1} & {2} & {3} \\
    {4} & {0} & {6} \\
    {7} & {8} & {9} \\
  \end{array}
\right]
$$

если вручую, то способом саррюса:
1*0*9 + 2*6*7 + 3*4*8 -7*0*3 -8*6*1 - 9*4*2 = 60

In [156]:
M = np.array([[1, 2, 3],
            [4, 0, 6],
            [7, 8, 9]])
det = np.linalg.det(M)
print(f'определитель матрицы\n{M}\n'
      f'равен {round(det, 2)}')

определитель матрицы
[[1 2 3]
 [4 0 6]
 [7 8 9]]
равен 60.0


## Задание 3

5.3. 1) Вычислите матрицу, обратную данной:
$$ 
\left[
  \begin{array}{ccc}
    {1} & {2} & {3} \\
    {4} & {0} & {6} \\
    {7} & {8} & {9} \\
  \end{array}
\right]
$$

если вручную, то 

находим определитель: 60 (отличен от нуля, значит, обратная матрица суещствует)

находим матрицу миноров

[[-48, -6, 32],
 [-6, -12, -6],
 [12, -6, -8]]

находим матрицк алгебраических дополнений

[[-48, 6, 32],
 [6, -12, 6],
 [12, 6, -8]]

находим тарнспонированную матрицу алгебраических дополнений

[[-48, 6, 12],
 [6, -12, 6],
 [32, 6, -8]]

находим обратную матрицу умножая на -1

[[48, -6, -12],
 [-6, 12, -6],
 [-32, -6, 8]]

проверил умножением - не получается едиинчная, вместо 1 по диагонали -60

тогда идем кодом:

In [158]:
import numpy as np
M = np.array([[1, 2, 3],
             [4, 0, 6],
             [7, 8, 9]])
M_i_manual = np.array([[48, -6, -12],
                    [-6, 12, -6],
                    [-32, -6, 8]])
print(f'проверка ручного способа:\n{np.matmul(M,M_i_manual)}')
M_i = np.linalg.inv(M)
print(f'\nобратная матрица: \n{M_i}\n')
print(f'\nпроверка расчета numpy библиотекой:\n{np.matmul(M,M_i)}')
# вроде, обратная найдена верно, вместо нулей минимальные значения - погрешности расчета

проверка ручного способа:
[[-60   0   0]
 [  0 -60   0]
 [  0   0 -60]]

обратная матрица: 
[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


проверка расчета numpy библиотекой:
[[ 1.00000000e+00 -2.77555756e-17  5.55111512e-17]
 [ 0.00000000e+00  1.00000000e+00  1.11022302e-16]
 [ 0.00000000e+00  2.77555756e-17  1.00000000e+00]]


5.3. 2) Приведите пример матрицы 4х4, ранг которой равен 1.

In [159]:
import numpy as np
# сгенерируем рандом:
M = np.array([[1, -1, 3, -1],
             [-1, 1, -1, 1],
             [1, -1, 1, -1],
             [-1, 1, -1, 1]])
print(f'например, марица: \n {M}\n')

например, марица: 
 [[ 1 -1  3 -1]
 [-1  1 -1  1]
 [ 1 -1  1 -1]
 [-1  1 -1  1]]



## Задание 4

5.4.
Вычислите скалярное произведение двух векторов:  
(1, 5)  и  (2, 8)

In [ ]:
import numpy as np

v_1 = np.array([1, 5])
v_2 = np.array([2, 8])
v_3 = np.dot(v_1, v_2)
print(f'скалярное произведение векторов \n{v_1}\n и \n{v_2}\nсоставляет: \n{v_3}')

## Задание 5

In [ ]:
5.5
Вычислите смешанное произведение трех векторов:
(1, 5, 0), (2, 8, 7) и (7, 1.5, 3) 

In [ ]:
v_1 = np.array([1, 5, 0])
v_2 = np.array([2, 8, 7])
v_3 = np.array([7, 1.5, 3])

M = np.array([[1, 5, 0],
             [2, 8, 7],
             [7, 1.5, 3]])
det = np.linalg.det(M)

print(f'скалярное произведение векторов (v1, v2, v3) составляет {round(det,2)}')

# Практическое задание №6

## Задание 1

1. Решите линейную систему:
$$ 
\left[
  \begin{array}{ccc}
    {1} & {2} & {3} \\
    {4} & {0} & {6} \\
    {7} & {8} & {9} \\
  \end{array}
\right]
* X = 
\begin{bmatrix}
           {12} \\
           {2} \\
           {1}
         \end{bmatrix}
$$

##### решаю интрументами python:

In [84]:
import numpy as np

In [85]:
A = np.array([[1, 2, 3],
            [4, 0, 6],
            [7, 8, 9]])
B = np.array([12, 2, 1])
X = np.linalg.solve(A, B)

In [86]:
print(f'x_1 = {round(solution[0],2)}\n',
      f'x_2 = {round(solution[1],2)}\n',
      f'x_3 = {round(solution[2],2)}\n')  

x_1 = -9.2
 x_2 = 0.9
 x_3 = 6.47



проверяю решение:

In [87]:
np.dot(A, X)

array([12.,  2.,  1.])

все верно

##### решаю методом обратной матрицы:

находим определитель:

In [88]:
det = 1*0*9 + 2*6*7 + 3*4*8 - 7*0*3 - 8*6*1 - 9*4*2
det

60

In [89]:
# проверяю
round(np.linalg.det(A),0)

60.0

определитель отличается от 0 -> нахожу обратную матрицу:

In [90]:
A_inv = np.linalg.inv(A)
A_inv

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

умножаю найденную обратную матрицу на вектор результата -> получаю вектор решения

In [91]:
X = np.dot(A_inv, B)

In [94]:
print(f'x_1 = {round(solution[0],2)}\n',
      f'x_2 = {round(solution[1],2)}\n',
      f'x_3 = {round(solution[2],2)}\n')  

x_1 = -9.2
 x_2 = 0.9
 x_3 = 6.47



проверяю:

In [93]:
np.dot(A, X)

array([12.,  2.,  1.])

все верно

## Задание 2

Найдите псевдорешение:

x + 2 * y - z = 1

3 * x - 4 * y = 7

8 * x - 5 * y + 2 * z = 12

2 * x - 5 * z = 7

11 * x + 4 * y - 7 * z = 15

numpy.linalg.lstsq решает для 2х неизвестных, как решать для 3х я не нашел, поэтому выражу одну переменную через другую: 

x = 1 + z - 2 * y

получаю:

- 10 * y + 3 * z = 4
- 21 * y + 10 * z = 4
- 4 * y - 3 * z = 5
- 18 * y + 4 * z = 4

отсюда записываю матрицы:

In [99]:
A = np.array([[-10, 3], 
              [-21, 10],
              [-4, -3],
              [-18, 4]])
B = np.array([4, 4, 5, 4])
rslt = np.linalg.lstsq(A, B)
rslt

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


(array([-0.46496043, -0.64543381]),
 array([6.77653811]),
 2,
 array([31.40961526,  5.33254808]))

из найденного y и z определяю x:

In [102]:
y = rslt[0][0]
z = rslt[0][1]
x = 1 + z - 2 * y

print(f'x = {x}, y = {y}, z = {z}')

x = 1.2844870606687109, y = -0.4649604334497755, z = -0.6454338062308401


оцениваю, вроде, похоже:

In [103]:
x + 2 * y - z 

1.0

In [105]:
3 * x - 4 * y

5.713302915805235

In [106]:
8 * x - 5 * y + 2 * z

11.309831040136885

In [107]:
2 * x - 5 * z 

5.796143152491622

In [108]:
11 * x + 4 * y - 7 * z

16.787552577172598

## Задание 3

3. Сколько решений имеет линейная система:
$$ 
\left[
  \begin{array}{ccc}
    {1} & {2} & {3} \\
    {4} & {5} & {6} \\
    {7} & {8} & {9} \\
  \end{array}
\right]
* X = 
\begin{bmatrix}
           {12} \\
           {2} \\
           {1}
         \end{bmatrix}
$$

Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее. 

In [110]:
A = np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])
B = np.array([12, 2, 1])

проверим, чему равен определитель матрицы А:

In [113]:
np.linalg.det(A)

-9.51619735392994e-16

есть подозрение, что это ошибка, проверим вручную:

In [115]:
det = 1*5*9 + 2*6*7 + 3*4*8 - 7*5*3 - 8*6*1 - 9*4*2
det

0

определитель равен нулю -> система несовместна

In [ ]:
x = np.linspace(-1, 3, 201)
plt.plot(x, 2 - 1.5 * x)
plt.plot(x, 0.75 * x - 0.25)
plt.xlabel('x')
plt.ylabel('y')
plt.grid(True)
plt.show()

меняю вектор решения так, чтобы система имела решения:

In [119]:
# ранг матрицы A
np.linalg.matrix_rank(A)

2

In [132]:
# ранг расширенной матрицы
C = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9],
             [12, 2, 1]])
np.linalg.matrix_rank(C)

3

In [135]:
# меняю расширенную матрицы так, чтобы она имела тот же ранг, что исходная
C = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9],
             [12, 12, 12]])
np.linalg.matrix_rank(C)

2

In [139]:
# отсюда определяю вектор результата
B = np.array([12, 12, 12])

In [142]:
print(f'решение:\n{np.linalg.solve(A, B)}')

решение:
[  2.4 -16.8  14.4]


## Задание 4

4. Вычислите LU-разложение матрицы:

$$ 
\left[
  \begin{array}{ccc}
    {1} & {2} & {3} \\
    {2} & {16} & {21} \\
    {4} & {28} & {73} \\
  \end{array}
\right]
$$

После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.

In [149]:
import scipy
import scipy.linalg

A = np.array([[1, 2, 3],
             [2, 16, 21],
             [4, 28, 73]])

# библитекой раскладываю
P, L, U = scipy.linalg.lu(A)
print(f'P:\n{P}\nL:\n{L}\nU:\n{U}')

P:
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L:
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
U:
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


придумываю вектор правых частей с учетом совпадения рангов матрицы с расширенной матрицей

In [150]:
np.linalg.matrix_rank(A)

3

In [151]:
C = np.array([[1, 2, 3],
             [2, 16, 21],
             [4, 28, 73],
             [1, 2, 4]])
np.linalg.matrix_rank(C)

3

In [ ]:
B = [1, 2, 4]

решаю слау:

In [153]:
print(f'решение:\n{np.linalg.solve(A, B)}')

решение:
[14.22222222 -0.44444444 -0.44444444]
